- name: Test Backend and Frontend
  hosts: localhost
  connection: local
  become: no
  vars:
    backend_port: 8000
    frontend_port: 80
    health_check_retries: 5
    health_check_delay: 10

  tasks:
    - name: Check Backend Health
      uri:
        url: "http://localhost:{{ backend_port }}/actuator/health"
        method: GET
        return_content: yes
        status_code: 200
      register: backend_health
      until: backend_health.status == 200 and '"status":"UP"' in backend_health.content
      retries: "{{ health_check_retries }}"
      delay: "{{ health_check_delay }}"
      changed_when: false

    - name: Test Backend API Endpoints
      uri:
        url: "http://localhost:{{ backend_port }}/api/students"
        method: GET
        return_content: yes
        status_code: [200, 401]
      register: api_check
      changed_when: false

    - name: Check Frontend Health
      uri:
        url: "http://localhost:{{ frontend_port }}"
        method: GET
        return_content: yes
        status_code: 200
      register: frontend_health
      until: frontend_health.status == 200 and 'Welcome to Scolarite' in frontend_health.content
      retries: "{{ health_check_retries }}"
      delay: "{{ health_check_delay }}"
      changed_when: false
